# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likes_number',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.ManyToManyField(to='home.Like'),
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.TextField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
