# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0002_auto_20180306_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
